### ISSUE TITLE
client.Packager

### ISSUE THREAD

**Issue by ailen1002** [hi-way/go-modbus#2]
st := modbus.NewSerialTransporter("COM3")
	st.Mode = serial.Mode{BaudRate: 19200}
	defer func() { _ = st.Close() }()
	// slave1
	c1 := modbus.NewClient(modbus.NewRtuPackager(1), st)
	_, results1, err1 := c1.ReadHoldingRegisters(1, 10)

	// change slave ID
	c1.Packager.SlaveId = 2

	// slave2
	_, results2, err2 := c1.ReadHoldingRegisters(1, 10)

	// change slave ID
	c1.Packager.SlaveId = 3

	// slave3
	_, results3, err3 := c1.ReadHoldingRegisters(1, 10)

client.Packager Can modify SlaveId externally with uppercase first letter. Communicate with different slave stations

**Comment by hi-way** [comment]
change slave ID
c2 := modbus.NewClient(modbus.NewRtuPackager(2), st)

**Comment by ailen1002** [comment]
I have modified my usage code according to your method, and everything seems to be working well now, thank you
